### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by Regis-Loyaute** [mertigoo/mern-youtube-clone#2]
Hello, i have a proxy issue on the client side, any idea why? the server is running on port 5000.

Proxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:5000/api/.
https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by mertkaandev** [comment]
Hi Regis Loyaute,

1. There is something I forgot to mention. When you run the project, create a "public" folder in the server folder. In the public folder, create two folders named "images" and "videos". These files are the locations of the files where the static files of the application are served and the public folder was ignored when uploading the project to Github:

server
  -> public
     -> images
     -> videos

2. If you still get the error after fixing this error, check the package.json file in the client folder. There is a proxy line at the bottom of the package.json file. The value of this line is "http://localhost:5000/api". This is the proxy feature of the React application. In other words, the application accepts requests from this address as a proxy. For this reason, API requests are sent to addresses such as "/video/update/" within the application. Actually this means:

http://localhost:5000/api/video/update

But since we have already specified the address as a proxy, we only send requests to the parts that come after api/ in the application.

Make sure the value of the proxy line is "http://localhost:5000/api" in the "package.json" file in the client folder. Likewise, don't change the addresses of api requests within the application.

Wrong:
axios.get("http://localhost:5000/api/trying");

True:
axios.get("/trying");
